apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-taskapi
spec:
  selector:
    app: {{ .Release.Name }}-taskapi
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
